name: Refresh Parquet cache

on:
  schedule:
    - cron: "*/15 * * * *"  # every 15 minutes (UTC)
  workflow_dispatch: {}      # allow manual runs

permissions:
  contents: write

concurrency:
  group: refresh-parquets
  cancel-in-progress: true

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true   # if using Git LFS for .parquet

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run refresh script
        env:
          KALSHI_API_KEY_ID: ${{ secrets.KALSHI_API_KEY_ID }}
          KALSHI_PRIVATE_KEY: ${{ secrets.KALSHI_PRIVATE_KEY }}
        run: |
          python scripts/refresh_parquets.py
          # If you prefer the optimized script instead, use:
          # python scripts/refresh_parquets_optimized.py
      
      # Data files are now excluded from git, so no need to commit them
      # The refresh script will update local data files for the app to use
