[server]
# Disable file watching to avoid inotify errors in cloud environments
fileWatcherType = "none"
# Force reload of modules
enableCaching = false
# Clear cache on restart
clearCacheOnRestart = true

[logger]
# Enable debug logging
level = "debug"

[browser]
# Disable automatic browser opening
gatherUsageStats = false

[client]
# Enable detailed error messages
showErrorDetails = true

[theme]
# Basic theme settings
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
